name: scuttlebutt
description: An anonymous social app for military personnel.

version: 1.0.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  provider: ^6.0.2
  google_sign_in: ^6.1.0
  geolocator: ^9.0.2 
  shared_preferences: ^2.1.1
  sign_in_with_apple: ^4.3.0
  flutter_webview_plugin: ^0.4.0
  http: ^0.13.5
  cloud_functions: ^4.3.2
  crypto: ^3.0.1
  flutter_web_auth: ^0.5.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/